// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV9688xStLaK2lN0I3yb4DVlB64PQZt40',
    appId: '1:72619545813:web:280e6390c1616f4f013e5c',
    messagingSenderId: '72619545813',
    projectId: 'aqi-app-5c475',
    authDomain: 'aqi-app-5c475.firebaseapp.com',
    storageBucket: 'aqi-app-5c475.firebasestorage.app',
    measurementId: 'G-RHZ1VJWRDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAn5A10oA0AGV48bBFdeZQiNSXDO3pQUs',
    appId: '1:72619545813:android:015a27476445244b013e5c',
    messagingSenderId: '72619545813',
    projectId: 'aqi-app-5c475',
    storageBucket: 'aqi-app-5c475.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3v-bMZ3n6u4cPgml6dopAKelPieguFMY',
    appId: '1:72619545813:ios:bd49ad33af327070013e5c',
    messagingSenderId: '72619545813',
    projectId: 'aqi-app-5c475',
    storageBucket: 'aqi-app-5c475.firebasestorage.app',
    iosBundleId: 'com.example.aqi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3v-bMZ3n6u4cPgml6dopAKelPieguFMY',
    appId: '1:72619545813:ios:bd49ad33af327070013e5c',
    messagingSenderId: '72619545813',
    projectId: 'aqi-app-5c475',
    storageBucket: 'aqi-app-5c475.firebasestorage.app',
    iosBundleId: 'com.example.aqi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV9688xStLaK2lN0I3yb4DVlB64PQZt40',
    appId: '1:72619545813:web:0b26bbd1d36fbd47013e5c',
    messagingSenderId: '72619545813',
    projectId: 'aqi-app-5c475',
    authDomain: 'aqi-app-5c475.firebaseapp.com',
    storageBucket: 'aqi-app-5c475.firebasestorage.app',
    measurementId: 'G-VLX22X7CJM',
  );
}
